const AppConstant = {
    CAKE_INFO_LIST: 'CAKE_INFO_LIST',
    CAKE_INFO_LIST_SERVICE_ERROR: 'CAKE_INFO_LIST_SERVICE_ERROR',
    SUBMIT_CAKE_SERVICE_ERROR: 'SUBMIT_CAKE_SERVICE_ERROR',
    CAKE_FORM_DATA: 'CAKE_FORM_DATA',
    SUBMIT_CAKE: 'SUBMIT_CAKE',
    CAKE_SUBMITTED: 'CAKE_SUBMITTED',
    CAKE_DETAILS: 'CAKE_DETAILS',
    CAKE_DETAILS_ERROR: 'CAKE_DETAILS_ERROR',
    RESET_DETAILS_DATA: 'RESET_DETAILS_DATA'
}
export const BASE_URL = 'http://ec2-52-209-201-89.eu-west-1.compute.amazonaws.com:5000/api/cakes';

export default AppConstant;